# Generated by Django 5.1.7 on 2025-03-17 19:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_profile_picture_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile_picture/default.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
